### ISSUE TITLE
Async confirm transaction

### ISSUE THREAD

**Issue by FabricioCabeca** [MoeCasts/laravel-wallet#1]
Hi there !

I was wondering if I could first set a transaction with confirmed = false and commit the transaction later, lets say you need to wait for an asynchronous response in order to deposit or withdraw, but you want to insert the transaction as unconfirmed and update upon confirmation.

Thanks for this nice library btw :)

**Comment by MoeCasts** [comment]
@FabricioCabeca Do you mean that write the transaction into cache, and flush the data into database if the data have not been changed in some time?

**Comment by FabricioCabeca** [comment]
Yep, this works fine, I was just wondering if refreshBalance would be overkill and perform badly, but maybe it is safer this way.
